// Copyright (c) 2012 The LevelDB Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file. See the AUTHORS file for names of contributors.

#include "leveldb/filter_policy.h"

#include "leveldb/slice.h"
#include "util/hash.h"
#include <immintrin.h>
#include <stdint.h>
#include <iostream>
#include <climits>
#include <cassert>

namespace leveldb {

namespace {
static uint32_t BloomHash(const Slice& key) {
  return Hash(key.data(), key.size(), 0xbc9f1d34);
}

class BloomFilterPolicy : public FilterPolicy {
 public:
  explicit BloomFilterPolicy(int bits_per_key) : bits_per_key_(bits_per_key) {
    // We intentionally round down to reduce probing cost a little bit
    k_ = static_cast<size_t>(bits_per_key * 0.69);  // 0.69 =~ ln(2)
    if (k_ < 1) k_ = 1;
    if (k_ > 30) k_ = 30;
  }

  const char* Name() const override { return "leveldb.BuiltinBloomFilter2"; }

  void CreateFilter(const Slice* keys, int n, std::string* dst) const override {
    // Compute bloom filter size (in both bits and bytes)
    size_t bits = n * bits_per_key_;

    // For small n, we can see a very high false positive rate.  Fix it
    // by enforcing a minimum bloom filter length.
    if (bits < 64) bits = 64;

    size_t bytes = (bits + 7) / 8;
    bits = bytes * 8;

    const size_t init_size = dst->size();
    dst->resize(init_size + bytes, 0);
    dst->push_back(static_cast<char>(k_));  // Remember # of probes in filter
    char* array = &(*dst)[init_size];
    for (int i = 0; i < n; i++) {
      // Use double-hashing to generate a sequence of hash values.
      // See analysis in [Kirsch,Mitzenmacher 2006].
      uint32_t h = BloomHash(keys[i]);
      const uint32_t delta = (h >> 17) | (h << 15);  // Rotate right 17 bits
      for (size_t j = 0; j < k_; j++) {
        const uint32_t bitpos = h % bits;
        array[bitpos / 8] |= (1 << (bitpos % 8));
        h += delta;
      }
    }
  }

  bool KeyMayMatch(const Slice& key, const Slice& bloom_filter) const override {
    const size_t len = bloom_filter.size();
    if (len < 2) return false;

    const char* array = bloom_filter.data();
    const size_t bits = (len - 1) * 8;

    // Use the encoded k so that we can read filters generated by
    // bloom filters created using different parameters.
    const size_t k = array[len - 1];
    if (k > 30) {
      // Reserved for potentially new encodings for short bloom filters.
      // Consider it a match.
      return true;
    }

    uint32_t h = BloomHash(key);
    const uint32_t delta = (h >> 17) | (h << 15);  // Rotate right 17 bits
    for (size_t j = 0; j < k; j++) {
      const uint32_t bitpos = h % bits;
      if ((array[bitpos / 8] & (1 << (bitpos % 8))) == 0) return false;
      h += delta;
    }
    return true;
  }

 protected:
  size_t bits_per_key_;
  size_t k_;
};

class VectorBloomFilterPolicy : public BloomFilterPolicy {
  public:
  VectorBloomFilterPolicy(int bits_per_key): BloomFilterPolicy(bits_per_key) {
  }

  void CreateFilter(const Slice* keys, int n, std::string* dst) const override {
    std::fprintf(stdout, "VectorBloomFilterPolicy::CreateFilter()\n");
    // Compute bloom filter size (in both bits and bytes)
    size_t bits = n * bits_per_key_;

    // For small n, we can see a very high false positive rate.  Fix it
    // by enforcing a minimum bloom filter length.
    if (bits < 64) bits = 64;
    bits = roundUp(bits);
    size_t bytes = bits / 8;
    assert(bits-1 <= INT_MAX);  // ensure mask can be represented by a signed integer.
    int32_t mask = bits-1;

    const size_t init_size = dst->size();
    dst->resize(init_size + bytes, 0);
    dst->push_back(static_cast<char>(k_));  // Remember # of probes in filter
    char* array = &(*dst)[init_size];
    for (int i = 0; i < n; i++) {
      // Use double-hashing to generate a sequence of hash values.
      // See analysis in [Kirsch,Mitzenmacher 2006].
      uint32_t h = BloomHash(keys[i]);
      const uint32_t delta = (h >> 17) | (h << 15);  // Rotate right 17 bits

      //setKey(array, h, delta, mask);
      for (size_t j = 0; j < k_; j++) {
        //const uint32_t bitpos = h % bits;
        // array[bitpos / 8] |= (1 << (bitpos % 8));

        const uint32_t bitpos = h & mask;
        array[bitpos >> 3] |= (1 << (bitpos & 7));
        h += delta;
      }
    }
  }

  private:

  // assume k = 8 for simplicity.
  void setKey(char* array, uint32_t h, uint32_t delta, uint32_t mask) const {
    __m512i mm_one = _mm512_set1_epi32(0x1);
    __m512i mm_three = _mm512_set1_epi32(0x3);
    __m512i mm_byte_mask = _mm512_set1_epi32(0x7);
    __m512i mm_times = _mm512_setr_epi32(0,1,2,3,4,5,6,7,0,1,2,3,4,5,6,7);
    __m512i mm_delta = _mm512_set1_epi32(delta);
    __m512i mm_mask = _mm512_set1_epi32(mask);
    __m512i mm_h = _mm512_set1_epi32(h);

    // _mm512_fmadd_ps() accepts __m512, instead of __m512i.
    // needs to cast between __m512 and __m512i.
    // bitpos = times * delta + h
    __m512 mm_new_h_s = _mm512_fmadd_ps(
                  _mm512_castsi512_ps(mm_times),
                  _mm512_castsi512_ps(mm_delta),
                  _mm512_castsi512_ps(mm_h));
    __m512i mm_bitpos = _mm512_castps_si512(mm_new_h_s);

    //        const uint32_t bitpos = h & mask;
    //    array[bitpos / 8] |= (1 << (bitpos & 7));
    mm_bitpos = _mm512_and_epi32(mm_bitpos, mm_mask);

    __m512i mm_byteId = _mm512_srlv_epi32(mm_bitpos, mm_three); // bitpos / 8

    __m512i mm_bit_index = _mm512_and_epi32(mm_bitpos, mm_byte_mask);
    __m512i mm_bytes = _mm512_sllv_epi32(mm_one, mm_bit_index);
    __m512i mm_old_value = _mm512_i32gather_epi32(mm_byteId, array, 1);
    __m512i mm_new_value = _mm512_or_epi32(mm_old_value, mm_bytes);
    _mm512_i32scatter_epi32(array, mm_byteId, mm_new_value, 1);
  }

};

}  // namespace

const FilterPolicy* NewBloomFilterPolicy(int bits_per_key) {
  return new BloomFilterPolicy(bits_per_key);
}

const FilterPolicy* NewVectorBloomFilterPolicy(int bits_per_key) {
  return new VectorBloomFilterPolicy(bits_per_key);
}

size_t roundUp(size_t n) {
  assert(n < SIZE_MAX/2);

  size_t m = 1;
  while(m < n)
    m *= 2;
  return m;
}

}  // namespace leveldb
